edition                  = "2024"
max_width                = 100
tab_spaces               = 4
newline_style            = "Unix"
reorder_imports          = true
reorder_modules          = true
use_field_init_shorthand = true
use_try_shorthand        = true
group_imports            = "StdExternalCrate"
imports_granularity      = "Crate"
