#:schema https://raw.githubusercontent.com/kjanat/zed-editor/03d96a897a2dbe98755c24375eec790b834eaaf7/crates/extension_api/schemas/extension.schema.json

id             = "turbo-zed"
name           = "Turborepo LSP"
version        = "0.1.0"
schema_version = 1
authors        = ["Kaj Kowalski <dev@kajkowalski.nl>"]
description    = "Tools and instant feedback for your build system"
repository     = "https://github.com/kjanat/zed-turbo"
themes         = []
icon_themes    = []
languages      = ["languages/turbo-json"]

[grammars.jsonc]
repository = "https://github.com/tree-sitter/tree-sitter-json"
rev        = "ee35a6ebefcef0c5c416c0d1ccec7370cfca5a24"         # v0.24.8 (supports comments)

[language_servers.turborepo-lsp]
languages = ["Turbo"]
# code_action_kinds = []

[language_servers.turborepo-lsp.language_ids]
"Turbo" = "jsonc"

[[capabilities]]
kind = "download_file"
host = "marketplace.visualstudio.com"
path = ["**"]

[[capabilities]]
kind = "download_file"
host = "*.gallerycdn.vsassets.io"
path = ["**"]

# [context_servers]
# [slash_commands]
